[general]
pidfile="burrow.pid"
stdout-logfile="burrow.out"
access-control-allow-origin="*"

[logging]
filename="logs/burrow.log"
level="info"
maxsize=100
maxbackups=30
maxage=10
use-localtime=false
use-compression=true

[zookeeper]
servers=[ "realtime-zk-0.realtime-zookeeper.crix:2181", "realtime-zk-0.realtime-zookeeper.crix:2181", "realtime-zk-0.realtime-zookeeper.crix:2181" ]
timeout=6
root-path="/burrow"

[client-profile.staging]
client-id="burrow-staging"
kafka-version="1.0.0"

[cluster.staging]
class-name="kafka"
servers=[ "realtime-kafka-0.broker.crix:9092", "realtime-kafka-1.broker.crix:9092", "realtime-kafka-2.broker.crix:9092" ]
client-profile="staging"
topic-refresh=120
offset-refresh=30

[consumer.staging]
class-name="kafka"
cluster="staging"
servers=[ "realtime-kafka-0.broker.crix:9092", "realtime-kafka-1.broker.crix:9092", "realtime-kafka-2.broker.crix:9092" ]
client-profile="staging"
group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
group-whitelist=""

[httpserver.default]
address=":8080"